#!/bin/bash
##
# . . .
# See the AWIPS II Master Rights File ("Master Rights File.pdf") for
# further licensing information.
##
##############################################################################
# This script allows users to extract ATCF "deck" file products from EDEX.
#
#     SOFTWARE HISTORY
#    
#    Date            Ticket#       Engineer       Description
#    ------------    ----------    -----------    --------------------------
#    10/24/2016      R22939        bhebbard       Initial Creation.
##############################################################################

# this allows you to run this script from outside of ./bin
path_to_script=`readlink -f $0`
RUN_FROM_DIR=`dirname $path_to_script`

BASE_AWIPS_DIR=`dirname $RUN_FROM_DIR`

# get the base environment
source ${RUN_FROM_DIR}/setup.env

# setup the environment needed to run the the Python
export LD_LIBRARY_PATH=${BASE_AWIPS_DIR}/src/lib:${PYTHON_INSTALL}/lib
export PYTHONPATH=${RUN_FROM_DIR}/src:$PYTHONPATH

# execute the ifpInit Python module
_PYTHON="${PYTHON_INSTALL}/bin/python"
_MODULE="${RUN_FROM_DIR}/src/atcf/retrieveAtcfDeck.py"

# quoting of '$@' is used to prevent command line interpretation 
#$_PYTHON $_MODULE -h ${DEFAULT_HOST} -p ${DEFAULT_PORT} "$@"
$_PYTHON $_MODULE "$@"

